### PR TITLE
uet_api: Fix conditional to set CQ entry tag

### PR DESCRIPTION
**Pull request by mjwilkins18**
`uet_rx_cq_post_entry` checks the completion type using the CQ entry format size. However, the checks require strictly *greater than* when they are equal for the largest type (e.g., for `FI_TAGGED`, `cq->format_size`=30 and `sizeof(struct fi_cq_tagged_entry)`=30, so the conditional fails when it should succeed.)

This fix is necessary to run the RCCL test over the uet libfabric provider.

### CODE REVIEW

**Comment by alexb-kt** [comment]
IMHO the text in the PR description should be in the commit message (which should survive forever in the git repo)

**Comment by mjwilkins18** [comment]
No problem! Apologies, I went to amend the commit message and did it in the wrong and created extra commits. If you can squash+merge and copy the PR description into the commit message, I would greatly appreciate it!

**Comment by alexb-kt** [comment]
*I* can't, because I don't have write permissions :)  But one can always force-push commits to a PR source branch (after e.g. a rebase).

**Comment by alexb-kt** [comment]
Perhaps like so: https://asciinema.org/a/LN6K5Q2DnunPJuomVKMlMtPWB

**Comment by mjwilkins18** [comment]
> _I_ can't, because I don't have write permissions :) But one can always force-push commits to a PR source branch (after e.g. a rebase).

Glad to know I am not alone 😄

**Comment by mjwilkins18** [comment]
Thanks for the walkthrough, fixed it!!

**Comment by insanum** [comment]
Thanks Mike!

**Pull request merged**
